
import type { ComponentType } from 'react';
import { PiggyBank, Car, Utensils, HeartPulse, Percent, Home, BrainCircuit, GraduationCap, TrendingUp, Footprints, Scale, Calculator, Calendar, Repeat, Atom, FlaskConical, Beaker, Ruler, Clock, Landmark, FileText, Wallet, Receipt, CreditCard, Recycle, Banknote, CandlestickChart, Briefcase, DraftingCompass, Cigarette, Droplets, Sun, Shirt, Building, Shovel, Box, Weight, Map, BookOpen, Beer, Dna, Leaf, Zap, Sigma, Coins, Award, Baby, UserCheck, Plane, ShoppingCart, TestTube2, Wallpaper, Activity, Moon, Soup, ShieldCheck, Handshake, Target, PaintRoller, Ratio, FunctionSquare, Pilcrow, Infinity, Equal, GitCompareArrows, BookText, AreaChart, CircuitBoard, HardDrive, Network, Gauge, Move, Square, Telescope, Text, Asterisk, WalletCards, Hourglass, BarChart3, TrendingDown, Syringe, Wheat, Sparkles, User, Users, Stethoscope, Wifi } from 'lucide-react';

export type Calculator = {
  name: string;
  slug: string;
  description: string;
  category: string;
  icon?: ComponentType<{ className?: string }>;
};

export const calculators: Calculator[] = [
  // Finance (30)
  {
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    description: 'Estimate your monthly mortgage payments, principal, and interest.',
    category: 'Finance',
    icon: Home,
  },
   {
    name: 'Mortgage Calculator (UK)',
    slug: 'mortgage-calculator-uk',
    description: 'Estimate mortgage payments for UK properties, including stamp duty considerations.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'Loan Calculator',
    slug: 'loan-calculator',
    description: 'Determine the repayment schedule for any type of fixed-rate loan.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'Student Loan Calculator',
    slug: 'student-loan-calculator',
    description: 'Estimate monthly payments and total interest for student loans.',
    category: 'Finance',
    icon: GraduationCap,
  },
  {
    name: 'Car Loan Calculator',
    slug: 'car-loan-calculator',
    description: 'Estimate your monthly car loan payments and total interest cost.',
    category: 'Finance',
    icon: Car,
  },
   {
    name: 'Amortization Calculator',
    slug: 'amortization-calculator',
    description: 'See how your loan payments are applied to principal and interest over time.',
    category: 'Finance',
    icon: FileText,
  },
  {
    name: 'Interest Calculator',
    slug: 'interest-calculator',
    description: 'Calculate simple and compound interest for a loan or investment.',
    category: 'Finance',
    icon: Percent,
  },
  {
    name: 'Compound Interest Calculator',
    slug: 'compound-interest-calculator',
    description: 'Calculate how much your investments will grow over time.',
    category: 'Finance',
    icon: TrendingUp,
  },
  {
    name: 'Investment Return Calculator',
    slug: 'investment-return-calculator',
    description: 'Evaluate the performance of an investment and see its growth.',
    category: 'Finance',
    icon: CandlestickChart,
  },
  {
    name: 'Pension Calculator',
    slug: 'pension-calculator',
    description: 'Estimate your future pension pot and potential retirement income.',
    category: 'Finance',
    icon: Landmark,
  },
  {
    name: 'Retirement Savings Calculator',
    slug: 'retirement-savings-calculator',
    description: 'Project your retirement savings growth and see if you are on track.',
    category: 'Finance',
    icon: Landmark,
  },
  {
    name: 'Inflation Calculator',
    slug: 'inflation-calculator',
    description: 'See how the value of money changes over time due to inflation.',
    category: 'Finance',
    icon: Banknote,
  },
  {
    name: 'Income Tax Calculator',
    slug: 'income-tax-calculator',
    description: 'Estimate your federal income tax liability based on your filing status and income.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Salary (Take-Home Pay) Calculator',
    slug: 'salary-calculator',
    description: 'Calculate your net pay by subtracting taxes and other deductions from your gross salary.',
    category: 'Finance',
    icon: Wallet,
  },
  {
    name: 'Sales Tax Calculator',
    slug: 'sales-tax-calculator',
    description: 'Quickly calculate sales tax for any amount and tax rate.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Credit Card Payoff Calculator',
    slug: 'credit-card-payoff-calculator',
    description: 'Find out how long it will take to pay off your credit card balance.',
    category: 'Finance',
    icon: CreditCard,
  },
  {
    name: 'Debt Payoff/Snowball Calculator',
    slug: 'debt-snowball-calculator',
    description: 'Create a plan to pay off multiple debts using the debt snowball method.',
    category: 'Finance',
    icon: Recycle,
  },
  {
    name: 'Refinance Calculator',
    slug: 'refinance-calculator',
    description: 'Determine if refinancing your mortgage could save you money.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'APR/APY Calculator',
    slug: 'apr-apy-calculator',
    description: 'Convert between Annual Percentage Rate (APR) and Annual Percentage Yield (APY).',
    category: 'Finance',
    icon: Percent,
  },
  {
    name: 'ROI (Return on Investment) Calculator',
    slug: 'roi-calculator',
    description: 'Calculate the profitability of an investment as a percentage.',
    category: 'Finance',
    icon: Briefcase,
  },
  {
    name: 'Time Value of Money (TVM) Calculator',
    slug: 'tvm-calculator',
    description: 'Solve for present value, future value, rate, or periods in financial calculations.',
    category: 'Finance',
    icon: Clock,
  },
  {
    name: 'Savings Goal Calculator',
    slug: 'savings-goal-calculator',
    description: 'Determine how much you need to save regularly to reach a financial goal.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'Investment Calculator',
    slug: 'investment-calculator',
    description: 'See how your investments can grow over time with compound interest.',
    category: 'Finance',
    icon: BrainCircuit,
  },
  {
    name: '401k Calculator',
    slug: '401k-calculator',
    description: 'Project your 401(k) growth and see if you are on track for retirement.',
    category: 'Finance',
    icon: Landmark,
  },
  {
    name: 'Budget Calculator',
    slug: 'budget-calculator',
    description: 'Create a monthly budget to manage your income and expenses.',
    category: 'Finance',
    icon: Wallet,
  },
  {
    name: 'Lease Calculator',
    slug: 'lease-calculator',
    description: 'Estimate the monthly payment for a car lease.',
    category: 'Finance',
    icon: Car,
  },
  {
    name: 'Paycheck Calculator',
    slug: 'paycheck-calculator',
    description: 'Calculate your take-home pay after federal and state taxes.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Net Worth Calculator',
    slug: 'net-worth-calculator',
    description: 'Calculate your net worth by subtracting liabilities from assets.',
    category: 'Finance',
    icon: UserCheck,
  },
  {
    name: 'Emergency Fund Calculator',
    slug: 'emergency-fund-calculator',
    description: 'Determine how much you need to save for an emergency fund.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'College Savings Calculator',
    slug: 'college-savings-calculator',
    description: 'Estimate how much you need to save for your child\'s college education.',
    category: 'Finance',
    icon: GraduationCap,
  },
  {
    name: 'Home Affordability Calculator',
    slug: 'home-affordability-calculator',
    description: 'Estimate how much house you can afford based on your income and debts.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'Discount Calculator',
    slug: 'discount-calculator',
    description: 'Calculate the final price after a discount and sales tax.',
    category: 'Finance',
    icon: ShoppingCart,
  },
  // Health & Fitness (29 -> 44)
  {
    name: 'BMI Calculator',
    slug: 'bmi-calculator',
    description: 'Calculate your Body Mass Index to assess your weight category.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'BMI Weight Loss Calculator',
    slug: 'bmi-weight-loss-calculator',
    description: 'Integrate BMI with weight loss goals to set calorie targets.',
    category: 'Health & Fitness',
    icon: TrendingDown,
  },
  {
    name: 'Blood Sugar Converter',
    slug: 'blood-sugar-converter',
    description: 'Convert blood glucose levels between mg/dL and mmol/L.',
    category: 'Health & Fitness',
    icon: Droplets,
  },
  {
    name: 'Calorie Calculator',
    slug: 'calorie-calculator',
    description: 'Estimate your daily calorie needs for maintaining, losing, or gaining weight.',
    category: 'Health & Fitness',
    icon: Utensils,
  },
  {
    name: 'Carb (Carbohydrate) Calculator',
    slug: 'carb-calculator',
    description: 'Calculate your recommended daily carbohydrate intake based on your goals.',
    category: 'Health & Fitness',
    icon: Wheat,
  },
  {
    name: 'Weight Watchers Points Calculator',
    slug: 'weight-watchers-points-calculator',
    description: 'Estimate points based on a legacy Weight Watchers formula for educational purposes.',
    category: 'Health & Fitness',
    icon: Scale,
  },
  {
    name: 'Pace Calculator',
    slug: 'pace-calculator',
    description: 'Calculate your running pace, finish time, or distance for your runs.',
    category: 'Health & Fitness',
    icon: Footprints
  },
  {
    name: 'BMR Calculator',
    slug: 'bmr-calculator',
    description: 'Calculate your Basal Metabolic Rate, the number of calories your body needs at rest.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Body Fat Calculator',
    slug: 'body-fat-calculator',
    description: 'Estimate your body fat percentage using the U.S. Navy method.',
    category: 'Health & Fitness',
    icon: Scale,
  },
  {
    name: 'Ideal Weight Calculator',
    slug: 'ideal-weight-calculator',
    description: 'Determine your healthy weight range based on your height and gender.',
    category: 'Health & Fitness',
    icon: Scale,
  },
  {
    name: 'TDEE Calculator',
    slug: 'tdee-calculator',
    description: 'Calculate your Total Daily Energy Expenditure to manage your weight.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Macro Calculator',
    slug: 'macro-calculator',
    description: 'Calculate your optimal daily intake of protein, carbs, and fats.',
    category: 'Health & Fitness',
    icon: Utensils,
  },
  {
    name: 'One Rep Max (1RM) Calculator',
    slug: 'one-rep-max-calculator',
    description: 'Estimate your one-repetition maximum for any weightlifting exercise.',
    category: 'Health & Fitness',
    icon: Weight,
  },
  {
    name: 'Pregnancy Due Date Calculator',
    slug: 'pregnancy-due-date-calculator',
    description: 'Estimate your baby\'s due date based on your last menstrual period.',
    category: 'Health & Fitness',
    icon: Baby,
  },
  {
    name: 'Ovulation Calculator',
    slug: 'ovulation-calculator',
    description: 'Predict your most fertile days to help you conceive.',
    category: 'Health & Fitness',
    icon: Calendar,
  },
  {
    name: 'BAC (Blood Alcohol Content) Calculator',
    slug: 'bac-calculator',
    description: 'Estimate your blood alcohol content based on your drinks and weight.',
    category: 'Health & Fitness',
    icon: Beer,
  },
  {
    name: 'Smoking Cost Calculator',
    slug: 'smoking-cost-calculator',
    description: 'Calculate how much money you spend on smoking over time.',
    category: 'Health & Fitness',
    icon: Cigarette,
  },
  {
    name: 'Water Intake Calculator',
    slug: 'water-intake-calculator',
    description: 'Determine your recommended daily water intake.',
    category: 'Health & Fitness',
    icon: Droplets,
  },
  {
    name: 'Heart Rate Zone Calculator',
    slug: 'heart-rate-zone-calculator',
    description: 'Calculate your target heart rate zones for exercise.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Running Time Predictor',
    slug: 'running-time-predictor',
    description: 'Predict your race times for different distances based on a recent race.',
    category: 'Health & Fitness',
    icon: Footprints,
  },
  {
    name: 'Wilks Score Calculator',
    slug: 'wilks-score-calculator',
    description: 'Calculate your Wilks score to compare your strength to other powerlifters.',
    category: 'Health & Fitness',
    icon: Award,
  },
  {
    name: 'Army Physical Fitness Test (APFT) Calculator',
    slug: 'apft-calculator',
    description: 'Calculate your score on the Army Physical Fitness Test.',
    category: 'Health & Fitness',
    icon: Award,
  },
  {
    name: 'Body Surface Area (BSA) Calculator',
    slug: 'bsa-calculator',
    description: 'Calculate the total surface area of a human body.',
    category: 'Health & Fitness',
    icon: UserCheck,
  },
  {
    name: 'Child Height Predictor',
    slug: 'child-height-predictor',
    description: 'Estimate how tall your child will be as an adult.',
    category: 'Health & Fitness',
    icon: Baby,
  },
  {
    name: 'VO2 Max Estimator',
    slug: 'vo2-max-estimator',
    description: 'Estimate your maximal oxygen uptake based on race performance.',
    category: 'Health & Fitness',
    icon: Activity,
  },
  {
    name: 'FFMI Calculator',
    slug: 'ffmi-calculator',
    description: 'Calculate your Fat-Free Mass Index, a measure of muscularity.',
    category: 'Health & Fitness',
    icon: Shirt,
  },
  {
    name: 'Sleep Calculator',
    slug: 'sleep-calculator',
    description: 'Determine the best time to wake up or go to sleep based on sleep cycles.',
    category: 'Health & Fitness',
    icon: Moon,
  },
  {
    name: 'Protein Intake Calculator',
    slug: 'protein-intake-calculator',
    description: 'Calculate your optimal daily protein intake for your body and goals.',
    category: 'Health & Fitness',
    icon: Soup,
  },
  {
    name: 'Advanced Hydration Calculator',
    slug: 'hydration-calculator',
    description: 'Calculate hydration needs based on activity and sweat rate.',
    category: 'Health & Fitness',
    icon: Droplets,
  },
  {
    name: 'Healthy Weight Gain Calculator',
    slug: 'healthy-weight-gain-calculator',
    description: 'Calculate the calorie surplus needed for a healthy rate of weight gain.',
    category: 'Health & Fitness',
    icon: Utensils,
  },
  {
    name: 'Cardiovascular Risk Calculator',
    slug: 'cardiovascular-risk-calculator',
    description: 'Estimate your 10-year risk of cardiovascular disease. For informational purposes only.',
    category: 'Health & Fitness',
    icon: ShieldCheck,
  },
  {
    name: 'Marine PFT Calculator',
    slug: 'marine-pft-calculator',
    description: 'Calculate your score for the Marine Corps Physical Fitness Test.',
    category: 'Health & Fitness',
    icon: Award,
  },
  {
    name: 'Navy PRT Calculator',
    slug: 'navy-prt-calculator',
    description: 'Calculate your score for the Navy Physical Readiness Test.',
    category: 'Health & Fitness',
    icon: Award,
  },
  // Math (29 -> 27)
  {
    name: 'Basic Calculator',
    slug: 'basic-calculator',
    description: 'A simple calculator for everyday arithmetic operations.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'P-value Calculator',
    slug: 'p-value-calculator',
    description: 'Calculate the P-value from a Z-score for statistical analysis.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Percentage Calculator',
    slug: 'percentage-calculator',
    description: 'Solve various percentage problems with ease.',
    category: 'Math',
    icon: Percent,
  },
  {
    name: 'Fraction Calculator',
    slug: 'fraction-calculator',
    description: 'Add, subtract, multiply, and divide fractions.',
    category: 'Math',
    icon: Beaker,
  },
  {
    name: 'Scientific Calculator',
    slug: 'scientific-calculator',
    description: 'Perform advanced calculations with trigonometric, logarithmic, and exponential functions.',
    category: 'Math',
    icon: Atom,
  },
  {
    name: 'Random Number Generator',
    slug: 'random-number-generator',
    description: 'Generate one or more random numbers within a specified range.',
    category: 'Math',
    icon: Zap,
  },
  {
    name: 'Standard Deviation Calculator',
    slug: 'standard-deviation-calculator',
    description: 'Calculate the standard deviation of a set of numbers.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Prime Number Calculator',
    slug: 'prime-number-calculator',
    description: 'Check if a number is prime and generate a list of prime numbers.',
    category: 'Math',
    icon: Dna,
  },
  {
    name: 'Greatest Common Divisor (GCD) Calculator',
    slug: 'gcd-calculator',
    description: 'Find the greatest common divisor of two or more numbers.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Least Common Multiple (LCM) Calculator',
    slug: 'lcm-calculator',
    description: 'Find the least common multiple of two or more numbers.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Logarithm Calculator',
    slug: 'logarithm-calculator',
    description: 'Calculate logarithms to any base.',
    category: 'Math',
    icon: BookOpen,
  },
  {
    name: 'Pythagorean Theorem Calculator',
    slug: 'pythagorean-theorem-calculator',
    description: 'Solve for any side of a right triangle using the Pythagorean theorem.',
    category: 'Math',
    icon: DraftingCompass,
  },
  {
    name: 'Quadratic Equation Solver',
    slug: 'quadratic-equation-solver',
    description: 'Find the roots of a quadratic equation (ax² + bx + c = 0).',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Factorial Calculator',
    slug: 'factorial-calculator',
    description: 'Calculate the factorial of a non-negative integer.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'Matrix Calculator',
    slug: 'matrix-calculator',
    description: 'Perform matrix operations like addition, subtraction, and multiplication.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'Mean, Median, Mode Calculator',
    slug: 'mean-median-mode-calculator',
    description: 'Calculate the mean, median, and mode of a set of numbers.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Number Sequence Calculator',
    slug: 'number-sequence-calculator',
    description: 'Identify and continue arithmetic or geometric number sequences.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Root Calculator',
    slug: 'root-calculator',
    description: 'Calculate the square root or nth root of a number.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Combinations and Permutations Calculator',
    slug: 'combinations-permutations-calculator',
    description: 'Calculate the number of combinations and permutations.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'GPA Calculator',
    slug: 'gpa-calculator',
    description: 'Calculate your Grade Point Average based on grades and credit hours.',
    category: 'Math',
    icon: GraduationCap,
  },
  {
    name: 'Graphing Calculator',
    slug: 'graphing-calculator',
    description: 'Plot functions and equations on an interactive graph.',
    category: 'Math',
    icon: AreaChart,
  },
  {
    name: 'Derivative Calculator',
    slug: 'derivative-calculator',
    description: 'Find the derivative of a function.',
    category: 'Math',
    icon: FunctionSquare,
  },
  {
    name: 'Integral Calculator',
    slug: 'integral-calculator',
    description: 'Find the definite or indefinite integral of a function.',
    category: 'Math',
    icon: Pilcrow,
  },
  {
    name: 'Limits Calculator',
    slug: 'limits-calculator',
    description: 'Evaluate the limit of a function as it approaches a value.',
    category: 'Math',
    icon: Infinity,
  },
  {
    name: 'Equation Solver',
    slug: 'equation-solver',
    description: 'Solve for variables in various types of equations.',
    category: 'Math',
    icon: Equal,
  },
  {
    name: 'Ratio Calculator',
    slug: 'ratio-calculator',
    description: 'Simplify ratios and solve for missing values in proportions.',
    category: 'Math',
    icon: Ratio,
  },
  {
    name: 'Significant Figures Calculator',
    slug: 'sig-fig-calculator',
    description: 'Round numbers to a specified number of significant figures.',
    category: 'Math',
    icon: BookText,
  },
  {
    name: 'Volume Calculator',
    slug: 'volume-calculator',
    description: 'Calculate the volume of common shapes like cubes, spheres, and cylinders.',
    category: 'Math',
    icon: Box,
  },
  // Time & Date
  {
    name: 'Age Calculator',
    slug: 'age-calculator',
    description: 'Find out your exact age in years, months, and days.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Date Difference Calculator',
    slug: 'date-difference-calculator',
    description: 'Calculate the number of days, months, and years between two dates.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Time Calculator',
    slug: 'time-calculator',
    description: 'Add or subtract time values in hours, minutes, and seconds.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Birthday Calculator',
    slug: 'birthday-calculator',
    description: 'Find out the day of the week you were born and how long until your next birthday.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Date to Day Calculator',
    slug: 'date-to-day-calculator',
    description: 'Find the day of the week for any given date in history or the future.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Working Days Calculator',
    slug: 'working-days-calculator',
    description: 'Calculate the number of working days between two dates, excluding weekends and holidays.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Time Duration Calculator',
    slug: 'time-duration-calculator',
    description: 'Calculate the duration between two points in time.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Countdown Timer',
    slug: 'countdown-timer',
    description: 'Set a countdown timer to a specific date and time.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Stopwatch',
    slug: 'stopwatch-calculator',
    description: 'An online stopwatch to time anything with precision.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Time Card Calculator',
    slug: 'time-card-calculator',
    description: 'Calculate total hours worked from a time card, including breaks.',
    category: 'Time & Date',
    icon: Briefcase,
  },

  // Career
  {
    name: 'Salary Negotiation Calculator',
    slug: 'salary-negotiation-calculator',
    description: 'Determine a target salary range based on current pay and market rates.',
    category: 'Career',
    icon: Handshake,
  },
  {
    name: 'Job Offer Comparison Calculator',
    slug: 'job-offer-comparison-calculator',
    description: 'Compare two job offers side-by-side, including benefits and other factors.',
    category: 'Career',
    icon: Briefcase,
  },
  {
    name: 'Freelance Rate Calculator',
    slug: 'freelance-rate-calculator',
    description: 'Determine an hourly or project rate based on your desired salary and expenses.',
    category: 'Career',
    icon: Target,
  },
  {
    name: 'Commute Cost Calculator',
    slug: 'commute-cost-calculator',
    description: 'Analyze the true cost of your daily commute, factoring in fuel, time, and vehicle wear.',
    category: 'Career',
    icon: Car,
  },
  {
    name: 'Hourly to Salary Converter',
    slug: 'hourly-to-salary-converter',
    description: 'Convert an hourly wage to an equivalent annual salary, and vice versa.',
    category: 'Career',
    icon: WalletCards,
  },
  {
    name: 'Should I Go Freelance?',
    slug: 'should-i-go-freelance-calculator',
    description: 'Compare a salaried position to freelance work to see the financial difference.',
    category: 'Career',
    icon: Briefcase,
  },
  {
    name: 'Work Hours Calculator',
    slug: 'work-hours-calculator',
    description: 'Track and sum up work hours for projects or pay periods.',
    category: 'Career',
    icon: Hourglass,
  },
  {
    name: 'Raise Percentage Calculator',
    slug: 'raise-percentage-calculator',
    description: 'Calculate the impact of a raise on your salary and take-home pay.',
    category: 'Career',
    icon: BarChart3,
  },
  {
    name: 'Overtime Pay Calculator',
    slug: 'overtime-pay-calculator',
    description: 'Calculate your total pay including regular and overtime hours.',
    category: 'Career',
    icon: Hourglass,
  },
  {
    name: 'Interview Prep Cost Calculator',
    slug: 'interview-prep-cost-calculator',
    description: 'Budget for expenses related to job interviews, such as travel and attire.',
    category: 'Career',
    icon: Briefcase,
  },

  // Everyday Utilities
  {
    name: 'Sun Angle Calculator',
    slug: 'sun-angle-calculator',
    description: 'Find the sun\'s position (azimuth and elevation) for any location and time.',
    category: 'Everyday Utilities',
    icon: Sun,
  },
  {
    name: 'Travel Time Calculator',
    slug: 'travel-time-calculator',
    description: 'Estimate the time it will take to travel a certain distance at a given speed.',
    category: 'Everyday Utilities',
    icon: Plane,
  },
  {
    name: 'Distance Calculator',
    slug: 'distance-calculator',
    description: 'Calculate the distance between two points on a map.',
    category: 'Everyday Utilities',
    icon: Map,
  },
  {
    name: 'Concrete Calculator',
    slug: 'concrete-calculator',
    description: 'Estimate the amount of concrete you need for a slab, footing, or post.',
    category: 'Everyday Utilities',
    icon: Shovel,
  },
  {
    name: 'Paint Calculator',
    slug: 'paint-calculator',
    description: 'Estimate how much paint you need to cover a certain area.',
    category: 'Everyday Utilities',
    icon: PaintRoller,
  },
  {
    name: 'Plant Spacing Calculator',
    slug: 'plant-spacing-calculator',
    description: 'Calculate how many plants you can fit in a given garden area.',
    category: 'Everyday Utilities',
    icon: Leaf,
  },
  {
    name: 'Wallpaper Calculator',
    slug: 'wallpaper-calculator',
    description: 'Determine how many rolls of wallpaper are needed for a room.',
    category: 'Everyday Utilities',
    icon: Wallpaper,
  },
  {
    name: 'Dilution Calculator',
    slug: 'dilution-calculator',
    description: 'Calculate how to dilute a concentrated solution to a desired final volume or concentration.',
    category: 'Everyday Utilities',
    icon: TestTube2,
  },
  {
    name: 'Ohm\'s Law Calculator',
    slug: 'ohms-law-calculator',
    description: 'Calculate Voltage, Current, Resistance, or Power using Ohm\'s Law.',
    category: 'Everyday Utilities',
    icon: CircuitBoard,
  },
  {
    name: 'Cost of Living Calculator',
    slug: 'cost-of-living-calculator',
    description: 'Compare the cost of living and required salary between two cities.',
    category: 'Everyday Utilities',
    icon: Building,
  },
  // Unit Converters
  {
    name: 'Universal Unit Converter',
    slug: 'unit-converter',
    description: 'Convert between various units of measurement (length, weight, temp, etc.).',
    category: 'Unit Converters',
    icon: GitCompareArrows,
  },
  {
    name: 'Currency Converter',
    slug: 'currency-converter',
    description: 'Convert between different currencies using the latest exchange rates.',
    category: 'Unit Converters',
    icon: Coins,
  },
  {
    name: 'Data Storage Converter',
    slug: 'data-storage-converter',
    description: 'Convert between bytes, kilobytes, megabytes, gigabytes, and terabytes.',
    category: 'Unit Converters',
    icon: HardDrive,
  },
  {
    name: 'Data Transfer Speed Converter',
    slug: 'data-transfer-speed-converter',
    description: 'Convert between different data transfer speed units (e.g., Mbps to MB/s).',
    category: 'Unit Converters',
    icon: Network,
  },
  {
    name: 'Bandwidth Calculator',
    slug: 'bandwidth-calculator',
    description: 'Estimate how long it will take to transfer a file based on its size and speed.',
    category: 'Unit Converters',
    icon: Wifi,
  },
  {
    name: 'Pressure Converter',
    slug: 'pressure-converter',
    description: 'Convert between pressure units like pascals, PSI, and atmospheres.',
    category: 'Unit Converters',
    icon: Gauge,
  },
  {
    name: 'Energy & Power Converter',
    slug: 'energy-power-converter',
    description: 'Convert between energy (joules, calories) and power (watts, horsepower) units.',
    category: 'Unit Converters',
    icon: Zap,
  },
  {
    name: 'Force Converter',
    slug: 'force-converter',
    description: 'Convert between units of force, such as Newtons and pounds-force.',
    category: 'Unit Converters',
    icon: Move,
  },
  {
    name: 'Speed Converter',
    slug: 'speed-converter',
    description: 'Convert between different units of speed, such as MPH, KPH, and m/s.',
    category: 'Unit Converters',
    icon: Gauge,
  },
  // Length and Area
  {
    name: 'Acreage Calculator',
    slug: 'acreage-calculator',
    description: 'Calculate the total acreage of a plot of land from its dimensions.',
    category: 'Length and Area',
    icon: Map,
  },
  {
    name: 'Area Converter',
    slug: 'area-converter',
    description: 'Convert between area units like square feet, square meters, and acres.',
    category: 'Length and Area',
    icon: Square,
  },
  {
    name: 'Ares to Hectares Converter',
    slug: 'ares-to-hectares-converter',
    description: 'Convert between ares and hectares for land measurement.',
    category: 'Length and Area',
    icon: Square,
  },
  {
    name: 'Astronomical Unit Calculator',
    slug: 'astronomical-unit-converter',
    description: 'Convert between astronomical units, light-years, and parsecs.',
    category: 'Length and Area',
    icon: Telescope,
  },
  {
    name: 'Decimeter to Meter Converter',
    slug: 'decimeter-to-meter-converter',
    description: 'Convert decimeters to meters and vice-versa.',
    category: 'Length and Area',
    icon: Ruler,
  },
  {
    name: 'Feet and Inches Calculator',
    slug: 'feet-and-inches-calculator',
    description: 'Add or subtract measurements in feet and inches.',
    category: 'Length and Area',
    icon: Ruler,
  },
  {
    name: 'Height in Inches Calculator',
    slug: 'height-in-inches-calculator',
    description: 'Quickly convert a height from feet and inches to total inches.',
    category: 'Length and Area',
    icon: Ruler,
  },
  {
    name: 'Inches to Fraction Calculator',
    slug: 'inches-to-fraction-calculator',
    description: 'Convert a decimal inch value to its nearest fraction equivalent.',
    category: 'Length and Area',
    icon: Text,
  },
  {
    name: 'Length Converter',
    slug: 'length-converter',
    description: 'Convert between various units of length, such as meters, feet, and miles.',
    category: 'Length and Area',
    icon: Ruler,
  },
  {
    name: 'Light Year Converter',
    slug: 'light-year-converter',
    description: 'Convert light years to other distance units like miles and kilometers.',
    category: 'Length and Area',
    icon: Telescope,
  },
  {
    name: 'Mesh to Micron Converter',
    slug: 'mesh-to-micron-converter',
    description: 'Convert between mesh size and micron rating for filters and sieves.',
    category: 'Length and Area',
    icon: Asterisk,
  },
  {
    name: 'Pixels to Inches Converter',
    slug: 'pixels-to-inches-converter',
    description: 'Convert pixels to inches based on screen resolution (DPI).',
    category: 'Length and Area',
    icon: Square,
  },
  {
    name: 'Area Calculator',
    slug: 'area-calculator',
    description: 'Calculate the area of common shapes like rectangles, circles, and triangles.',
    category: 'Length and Area',
    icon: Square,
  },
];

const allCategories = [...new Set(calculators.map(c => c.category))];
const otherCategory = 'Other';
// Sort all categories except 'Other' alphabetically
const mainCategories = allCategories.filter(c => c !== otherCategory).sort();
// Add 'Other' to the end of the list if it exists
if (allCategories.includes(otherCategory)) {
  mainCategories.push(otherCategory);
}

export const calculatorCategories = mainCategories;
export const calculatorNames = calculators.map(c => c.name);
