import type { ComponentType } from 'react';
import { PiggyBank, Car, Utensils, HeartPulse, Percent, Home, BrainCircuit, GraduationCap, TrendingUp, Footprints, Scale, Calculator, Calendar, Repeat, Atom, FlaskConical, Beaker, Ruler, Clock, Landmark, FileText, Wallet, Receipt, CreditCard, Recycle, Banknote, CandlestickChart, Briefcase, DraftingCompass, Cigarette, Droplets, Sun, Shirt, Building, Shovel, Box, Weight, Map, BookOpen, Beer, Dna, Leaf, Zap, Sigma, Coins, Award, Baby, UserCheck, Plane, ShoppingCart, TestTube2, Ratio, Code, Timer, Binary, Server, BriefcaseMedical, Handshake, Target, SlidersHorizontal, Settings, PaintRoller, Cable, CircuitBoard, Wallpaper } from 'lucide-react';

export type Calculator = {
  name: string;
  slug: string;
  description: string;
  category: string;
  icon?: ComponentType<{ className?: string }>;
};

export const calculators: Calculator[] = [
  // Finance (30)
  {
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    description: 'Estimate your monthly mortgage payments, principal, and interest.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'Loan Calculator',
    slug: 'loan-calculator',
    description: 'Determine the repayment schedule for any type of fixed-rate loan.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'Car Loan Calculator',
    slug: 'car-loan-calculator',
    description: 'Estimate your monthly car loan payments and total interest cost.',
    category: 'Finance',
    icon: Car,
  },
   {
    name: 'Amortization Calculator',
    slug: 'amortization-calculator',
    description: 'See how your loan payments are applied to principal and interest over time.',
    category: 'Finance',
    icon: FileText,
  },
  {
    name: 'Interest Calculator',
    slug: 'interest-calculator',
    description: 'Calculate simple and compound interest for a loan or investment.',
    category: 'Finance',
    icon: Percent,
  },
  {
    name: 'Compound Interest Calculator',
    slug: 'compound-interest-calculator',
    description: 'Calculate how much your investments will grow over time.',
    category: 'Finance',
    icon: TrendingUp,
  },
  {
    name: 'Investment Return Calculator',
    slug: 'investment-return-calculator',
    description: 'Evaluate the performance of an investment and see its growth.',
    category: 'Finance',
    icon: CandlestickChart,
  },
  {
    name: 'Retirement Savings Calculator',
    slug: 'retirement-savings-calculator',
    description: 'Project your retirement savings growth and see if you are on track.',
    category: 'Finance',
    icon: Landmark,
  },
  {
    name: 'Inflation Calculator',
    slug: 'inflation-calculator',
    description: 'See how the value of money changes over time due to inflation.',
    category: 'Finance',
    icon: Banknote,
  },
  {
    name: 'Income Tax Calculator',
    slug: 'income-tax-calculator',
    description: 'Estimate your federal income tax liability based on your filing status and income.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Salary (Take-Home Pay) Calculator',
    slug: 'salary-calculator',
    description: 'Calculate your net pay by subtracting taxes and other deductions from your gross salary.',
    category: 'Finance',
    icon: Wallet,
  },
  {
    name: 'Sales Tax Calculator',
    slug: 'sales-tax-calculator',
    description: 'Quickly calculate sales tax for any amount and tax rate.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Credit Card Payoff Calculator',
    slug: 'credit-card-payoff-calculator',
    description: 'Find out how long it will take to pay off your credit card balance.',
    category: 'Finance',
    icon: CreditCard,
  },
  {
    name: 'Debt Payoff/Snowball Calculator',
    slug: 'debt-snowball-calculator',
    description: 'Create a plan to pay off multiple debts using the debt snowball method.',
    category: 'Finance',
    icon: Recycle,
  },
  {
    name: 'Refinance Calculator',
    slug: 'refinance-calculator',
    description: 'Determine if refinancing your mortgage could save you money.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'APR/APY Calculator',
    slug: 'apr-apy-calculator',
    description: 'Convert between Annual Percentage Rate (APR) and Annual Percentage Yield (APY).',
    category: 'Finance',
    icon: Percent,
  },
  {
    name: 'ROI (Return on Investment) Calculator',
    slug: 'roi-calculator',
    description: 'Calculate the profitability of an investment as a percentage.',
    category: 'Finance',
    icon: Briefcase,
  },
  {
    name: 'Time Value of Money (TVM) Calculator',
    slug: 'tvm-calculator',
    description: 'Solve for present value, future value, rate, or periods in financial calculations.',
    category: 'Finance',
    icon: Clock,
  },
  {
    name: 'Savings Goal Calculator',
    slug: 'savings-goal-calculator',
    description: 'Determine how much you need to save regularly to reach a financial goal.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'Investment Calculator',
    slug: 'investment-calculator',
    description: 'See how your investments can grow over time with compound interest.',
    category: 'Finance',
    icon: BrainCircuit,
  },
  {
    name: '401k Calculator',
    slug: '401k-calculator',
    description: 'Project your 401(k) growth and see if you are on track for retirement.',
    category: 'Finance',
    icon: Landmark,
  },
  {
    name: 'Budget Calculator',
    slug: 'budget-calculator',
    description: 'Create a monthly budget to manage your income and expenses.',
    category: 'Finance',
    icon: Wallet,
  },
  {
    name: 'Lease Calculator',
    slug: 'lease-calculator',
    description: 'Estimate the monthly payment for a car lease.',
    category: 'Finance',
    icon: Car,
  },
  {
    name: 'Currency Converter',
    slug: 'currency-converter',
    description: 'Convert between different currencies using the latest exchange rates.',
    category: 'Finance',
    icon: Coins,
  },
  {
    name: 'Paycheck Calculator',
    slug: 'paycheck-calculator',
    description: 'Calculate your take-home pay after federal and state taxes.',
    category: 'Finance',
    icon: Receipt,
  },
  {
    name: 'Net Worth Calculator',
    slug: 'net-worth-calculator',
    description: 'Calculate your net worth by subtracting liabilities from assets.',
    category: 'Finance',
    icon: UserCheck,
  },
  {
    name: 'Emergency Fund Calculator',
    slug: 'emergency-fund-calculator',
    description: 'Determine how much you need to save for an emergency fund.',
    category: 'Finance',
    icon: PiggyBank,
  },
  {
    name: 'College Savings Calculator',
    slug: 'college-savings-calculator',
    description: 'Estimate how much you need to save for your child\'s college education.',
    category: 'Finance',
    icon: GraduationCap,
  },
  {
    name: 'Home Affordability Calculator',
    slug: 'home-affordability-calculator',
    description: 'Estimate how much house you can afford based on your income and debts.',
    category: 'Finance',
    icon: Home,
  },
  {
    name: 'Discount Calculator',
    slug: 'discount-calculator',
    description: 'Calculate the final price after a discount and sales tax.',
    category: 'Finance',
    icon: ShoppingCart,
  },
  // Health & Fitness (20)
  {
    name: 'BMI Calculator',
    slug: 'bmi-calculator',
    description: 'Calculate your Body Mass Index to assess your weight category.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Calorie Calculator',
    slug: 'calorie-calculator',
    description: 'Estimate your daily calorie needs for maintaining, losing, or gaining weight.',
    category: 'Health & Fitness',
    icon: Utensils,
  },
  {
    name: 'Pace Calculator',
    slug: 'pace-calculator',
    description: 'Calculate your running pace, finish time, or distance for your runs.',
    category: 'Health & Fitness',
    icon: Footprints
  },
  {
    name: 'BMR Calculator',
    slug: 'bmr-calculator',
    description: 'Calculate your Basal Metabolic Rate, the number of calories your body needs at rest.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Body Fat Calculator',
    slug: 'body-fat-calculator',
    description: 'Estimate your body fat percentage using the U.S. Navy method.',
    category: 'Health & Fitness',
    icon: Scale,
  },
  {
    name: 'Ideal Weight Calculator',
    slug: 'ideal-weight-calculator',
    description: 'Determine your healthy weight range based on your height and gender.',
    category: 'Health & Fitness',
    icon: Scale,
  },
  {
    name: 'TDEE Calculator',
    slug: 'tdee-calculator',
    description: 'Calculate your Total Daily Energy Expenditure to manage your weight.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Macro Calculator',
    slug: 'macro-calculator',
    description: 'Calculate your optimal daily intake of protein, carbs, and fats.',
    category: 'Health & Fitness',
    icon: Utensils,
  },
  {
    name: 'One Rep Max (1RM) Calculator',
    slug: 'one-rep-max-calculator',
    description: 'Estimate your one-repetition maximum for any weightlifting exercise.',
    category: 'Health & Fitness',
    icon: Weight,
  },
  {
    name: 'Pregnancy Due Date Calculator',
    slug: 'pregnancy-due-date-calculator',
    description: 'Estimate your baby\'s due date based on your last menstrual period.',
    category: 'Health & Fitness',
    icon: Baby,
  },
  {
    name: 'Ovulation Calculator',
    slug: 'ovulation-calculator',
    description: 'Predict your most fertile days to help you conceive.',
    category: 'Health & Fitness',
    icon: Calendar,
  },
  {
    name: 'BAC (Blood Alcohol Content) Calculator',
    slug: 'bac-calculator',
    description: 'Estimate your blood alcohol content based on your drinks and weight.',
    category: 'Health & Fitness',
    icon: Beer,
  },
  {
    name: 'Smoking Cost Calculator',
    slug: 'smoking-cost-calculator',
    description: 'Calculate how much money you spend on smoking over time.',
    category: 'Health & Fitness',
    icon: Cigarette,
  },
  {
    name: 'Water Intake Calculator',
    slug: 'water-intake-calculator',
    description: 'Determine your recommended daily water intake.',
    category: 'Health & Fitness',
    icon: Droplets,
  },
  {
    name: 'Heart Rate Zone Calculator',
    slug: 'heart-rate-zone-calculator',
    description: 'Calculate your target heart rate zones for exercise.',
    category: 'Health & Fitness',
    icon: HeartPulse,
  },
  {
    name: 'Running Time Predictor',
    slug: 'running-time-predictor',
    description: 'Predict your race times for different distances based on a recent race.',
    category: 'Health & Fitness',
    icon: Footprints,
  },
  {
    name: 'Wilks Score Calculator',
    slug: 'wilks-score-calculator',
    description: 'Calculate your Wilks score to compare your strength to other powerlifters.',
    category: 'Health & Fitness',
    icon: Award,
  },
  {
    name: 'Army Physical Fitness Test (APFT) Calculator',
    slug: 'apft-calculator',
    description: 'Calculate your score on the Army Physical Fitness Test.',
    category: 'Health & Fitness',
    icon: Award,
  },
  {
    name: 'Body Surface Area (BSA) Calculator',
    slug: 'bsa-calculator',
    description: 'Calculate the total surface area of a human body.',
    category: 'Health & Fitness',
    icon: UserCheck,
  },
  {
    name: 'Child Height Predictor',
    slug: 'child-height-predictor',
    description: 'Estimate how tall your child will be as an adult.',
    category: 'Health & Fitness',
    icon: Baby,
  },
  // Math (20)
  {
    name: 'Basic Calculator',
    slug: 'basic-calculator',
    description: 'A simple calculator for everyday arithmetic operations.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'Percentage Calculator',
    slug: 'percentage-calculator',
    description: 'Solve various percentage problems with ease.',
    category: 'Math',
    icon: Percent,
  },
  {
    name: 'Fraction Calculator',
    slug: 'fraction-calculator',
    description: 'Add, subtract, multiply, and divide fractions.',
    category: 'Math',
    icon: Beaker,
  },
  {
    name: 'Scientific Calculator',
    slug: 'scientific-calculator',
    description: 'Perform advanced calculations with trigonometric, logarithmic, and exponential functions.',
    category: 'Math',
    icon: Atom,
  },
  {
    name: 'Random Number Generator',
    slug: 'random-number-generator',
    description: 'Generate one or more random numbers within a specified range.',
    category: 'Math',
    icon: Zap,
  },
  {
    name: 'Standard Deviation Calculator',
    slug: 'standard-deviation-calculator',
    description: 'Calculate the standard deviation of a set of numbers.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Area Calculator',
    slug: 'area-calculator',
    description: 'Calculate the area of various shapes like circles, squares, and triangles.',
    category: 'Math',
    icon: DraftingCompass,
  },
  {
    name: 'Volume Calculator',
    slug: 'volume-calculator',
    description: 'Calculate the volume of 3D shapes like spheres, cubes, and cylinders.',
    category: 'Math',
    icon: Box,
  },
  {
    name: 'Prime Number Calculator',
    slug: 'prime-number-calculator',
    description: 'Check if a number is prime and generate a list of prime numbers.',
    category: 'Math',
    icon: Dna,
  },
  {
    name: 'Greatest Common Divisor (GCD) Calculator',
    slug: 'gcd-calculator',
    description: 'Find the greatest common divisor of two or more numbers.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Least Common Multiple (LCM) Calculator',
    slug: 'lcm-calculator',
    description: 'Find the least common multiple of two or more numbers.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Logarithm Calculator',
    slug: 'logarithm-calculator',
    description: 'Calculate logarithms to any base.',
    category: 'Math',
    icon: BookOpen,
  },
  {
    name: 'Pythagorean Theorem Calculator',
    slug: 'pythagorean-theorem-calculator',
    description: 'Solve for any side of a right triangle using the Pythagorean theorem.',
    category: 'Math',
    icon: DraftingCompass,
  },
  {
    name: 'Quadratic Equation Solver',
    slug: 'quadratic-equation-solver',
    description: 'Find the roots of a quadratic equation (ax² + bx + c = 0).',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Factorial Calculator',
    slug: 'factorial-calculator',
    description: 'Calculate the factorial of a non-negative integer.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'Matrix Calculator',
    slug: 'matrix-calculator',
    description: 'Perform matrix operations like addition, subtraction, and multiplication.',
    category: 'Math',
    icon: Calculator,
  },
  {
    name: 'Mean, Median, Mode Calculator',
    slug: 'mean-median-mode-calculator',
    description: 'Calculate the mean, median, and mode of a set of numbers.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Number Sequence Calculator',
    slug: 'number-sequence-calculator',
    description: 'Identify and continue arithmetic or geometric number sequences.',
    category: 'Math',
    icon: Repeat,
  },
  {
    name: 'Root Calculator',
    slug: 'root-calculator',
    description: 'Calculate the square root or nth root of a number.',
    category: 'Math',
    icon: Sigma,
  },
  {
    name: 'Combinations and Permutations Calculator',
    slug: 'combinations-permutations-calculator',
    description: 'Calculate the number of combinations and permutations.',
    category: 'Math',
    icon: Repeat,
  },
  // Time & Date (10)
  {
    name: 'Age Calculator',
    slug: 'age-calculator',
    description: 'Find out your exact age in years, months, and days.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Date Difference Calculator',
    slug: 'date-difference-calculator',
    description: 'Calculate the number of days, months, and years between two dates.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Time Calculator',
    slug: 'time-calculator',
    description: 'Add or subtract time values in hours, minutes, and seconds.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Birthday Calculator',
    slug: 'birthday-calculator',
    description: 'Find out the day of the week you were born and how long until your next birthday.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Date to Day Calculator',
    slug: 'date-to-day-calculator',
    description: 'Find the day of the week for any given date in history or the future.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Working Days Calculator',
    slug: 'working-days-calculator',
    description: 'Calculate the number of working days between two dates, excluding weekends and holidays.',
    category: 'Time & Date',
    icon: Calendar,
  },
  {
    name: 'Time Duration Calculator',
    slug: 'time-duration-calculator',
    description: 'Calculate the duration between two points in time.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Countdown Timer',
    slug: 'countdown-timer',
    description: 'Set a countdown timer to a specific date and time.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Stopwatch',
    slug: 'stopwatch-calculator',
    description: 'An online stopwatch to time anything with precision.',
    category: 'Time & Date',
    icon: Clock,
  },
  {
    name: 'Time Card Calculator',
    slug: 'time-card-calculator',
    description: 'Calculate total hours worked from a time card, including breaks.',
    category: 'Time & Date',
    icon: Briefcase,
  },
  // Everyday Utilities (10 -> 8)
  {
    name: 'Tip Calculator',
    slug: 'tip-calculator',
    description: 'Quickly calculate the tip for a bill for any number of people.',
    category: 'Everyday Utilities',
    icon: Utensils,
  },
  {
    name: 'Fuel Cost Calculator',
    slug: 'fuel-cost-calculator',
    description: 'Estimate the total fuel cost for a road trip based on distance and MPG.',
    category: 'Everyday Utilities',
    icon: Car,
  },
  {
    name: 'GPA Calculator',
    slug: 'gpa-calculator',
    description: 'Calculate your Grade Point Average based on grades and credit hours.',
    category: 'Everyday Utilities',
    icon: GraduationCap,
  },
  {
    name: 'Sun Angle Calculator',
    slug: 'sun-angle-calculator',
    description: 'Find the sun\'s position (azimuth and elevation) for any location and time.',
    category: 'Everyday Utilities',
    icon: Sun,
  },
  {
    name: 'Travel Time Calculator',
    slug: 'travel-time-calculator',
    description: 'Estimate the time it will take to travel a certain distance at a given speed.',
    category: 'Everyday Utilities',
    icon: Plane,
  },
  {
    name: 'Distance Calculator',
    slug: 'distance-calculator',
    description: 'Calculate the distance between two points on a map.',
    category: 'Everyday Utilities',
    icon: Map,
  },
  {
    name: 'Cost of Living Calculator',
    slug: 'cost-of-living-calculator',
    description: 'Compare the cost of living between two cities.',
    category: 'Everyday Utilities',
    icon: Building,
  },
  {
    name: 'Dilution Calculator',
    slug: 'dilution-calculator',
    description: 'Calculate how to dilute a concentrated solution to a desired final volume or concentration.',
    category: 'Everyday Utilities',
    icon: TestTube2,
  },
  // Home & Garden (4)
   {
    name: 'Concrete Calculator',
    slug: 'concrete-calculator',
    description: 'Estimate the amount of concrete you need for a slab, footing, or post.',
    category: 'Home & Garden',
    icon: Shovel,
  },
  {
    name: 'Paint Calculator',
    slug: 'paint-calculator',
    description: 'Estimate how much paint you need to cover a certain area.',
    category: 'Home & Garden',
    icon: PaintRoller,
  },
  {
    name: 'Plant Spacing Calculator',
    slug: 'plant-spacing-calculator',
    description: 'Calculate how many plants you can fit in a given garden area.',
    category: 'Home & Garden',
    icon: Leaf,
  },
  {
    name: 'Wallpaper Calculator',
    slug: 'wallpaper-calculator',
    description: 'Determine how many rolls of wallpaper are needed for a room.',
    category: 'Home & Garden',
    icon: Wallpaper,
  },
  // Electronics (2)
  {
    name: 'Ohm\'s Law Calculator',
    slug: 'ohms-law-calculator',
    description: 'Calculate Voltage, Current, Resistance, or Power using Ohm\'s Law.',
    category: 'Electronics',
    icon: CircuitBoard,
  },
  {
    name: 'Data Transfer Time Calculator',
    slug: 'data-transfer-time-calculator',
    description: 'Estimate how long it will take to transfer a file over a specific network speed.',
    category: 'Electronics',
    icon: Server,
  },
  // Developer (5)
  {
    name: 'CSS Unit Converter',
    slug: 'css-unit-converter',
    description: 'Convert between px, em, rem, %, and viewport units for responsive web design.',
    category: 'Developer',
    icon: Code,
  },
  {
    name: 'Color Converter',
    slug: 'color-converter',
    description: 'Convert color codes between HEX, RGB, and HSL formats.',
    category: 'Developer',
    icon: SlidersHorizontal,
  },
  {
    name: 'Aspect Ratio Calculator',
    slug: 'aspect-ratio-calculator',
    description: 'Calculate dimensions for images or videos to maintain a specific aspect ratio.',
    category: 'Developer',
    icon: Ratio,
  },
  {
    name: 'Timestamp Converter',
    slug: 'timestamp-converter',
    description: 'Convert Unix timestamps to human-readable dates and back.',
    category: 'Developer',
    icon: Timer,
  },
  {
    name: 'Base64 Encoder/Decoder',
    slug: 'base64-encoder',
    description: 'Encode files or text into Base64 strings and decode them back.',
    category: 'Developer',
    icon: Binary,
  },
  {
    name: 'Cron Job Generator',
    slug: 'cron-job-generator',
    description: 'Create complex cron job schedules with a user-friendly interface.',
    category: 'Developer',
    icon: Settings,
  },
  // Career (3)
  {
    name: 'Salary Negotiation Calculator',
    slug: 'salary-negotiation-calculator',
    description: 'Determine a target salary range based on current pay and market rates.',
    category: 'Career',
    icon: Handshake,
  },
  {
    name: 'Job Offer Comparison Calculator',
    slug: 'job-offer-comparison-calculator',
    description: 'Compare two job offers side-by-side, including benefits and other factors.',
    category: 'Career',
    icon: BriefcaseMedical,
  },
  {
    name: 'Freelance Rate Calculator',
    slug: 'freelance-rate-calculator',
    description: 'Determine an hourly or project rate based on your desired salary and expenses.',
    category: 'Career',
    icon: Target,
  },
];

export const calculatorCategories = [...new Set(calculators.map(c => c.category))].sort();
export const calculatorNames = calculators.map(c => c.name);
